[package]
name = "rust-lambda"
version = "0.1.0"
edition = "2021"

# Binary needs to be named "bootstrap" since custom runtime will look for /var/task/bootstrap
[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
lambda_runtime = "0.5.0"
serde_json = "1.0.79"
tokio = "1.17.0"
